open-contracting/cove-oc4ids

cove_oc4ids/templates/cove_oc4ids/base.html, cove_oc4ids/templates/cove_oc4ids/explore.html
Misc updates to content in templates after initial feedback see Issue #2
=> templates Update with new content and corrections

cove_oc4ids/templates/cove_oc4ids/explore.html
=> templates Corrections to copy on headlines section

cove_oc4ids/views.py
=> Make schema for conversions correct

.travis.yml, cove_oc4ids/views.py, tests/test_browser.py
Basic test to see if the cove instance runs and shows the home page
=> Add basic run sanity test

cove_oc4ids/templates/cove_oc4ids/base.html
=> templates base Add example json link load the json doc into cove

cove_oc4ids/templates/cove_oc4ids/explore.html
=> templates explore Add link to publication policy if available

cove_oc4ids/templates/cove_oc4ids/base.html
=> templates base Fix typo oc4ds to oc4ids

.travis.yml, cove_oc4ids/test_functional.py, requirements.in, requirements.txt, requirements_dev.in, requirements_dev.txt
Also: Not all tests were being run. I had to fix a test that seems to have been copied from BODS; I'm not sure what it's supposed to be testing, but at least it passes now.
=> Update Django, use pypi releases, add coveralls

README.md
@duncandewhurst Could you check these instructions are sufficient for you to get the tests running.
=> readme: Add section on how to run the tests

requirements_dev.in, requirements_dev.txt
https://github.com/open-contracting/cove-oc4ids/issues/60
=> requirements_dev.in does not include pip-tools

cove_project/settings.py
Fixes https://github.com/open-contracting/deploy/issues/53
=> settings: Add USE_X_FORWARDED_HOST

cove_project/settings.py
To avoid clashing with the other Cove on the same domain.
https://github.com/open-contracting/deploy/issues/188
=> Set Session and SCRF cookie name

cove_oc4ids/views.py
Continuation of 7c9780f4ed67715a0a06892cfa1984025b6fcd78
Fixes https://github.com/open-contracting/cove-oc4ids/issues/66
=> views: Remove 'release' from variable name

README.md, cove_project/settings.py, requirements.in, requirements.txt
Add with defaults as suggested in Django documentation.
Related: https://github.com/open-contracting/cove-ocds/issues/90
=> cove_project: settings: Add memcached backend if not in DEBUG mode

cove_oc4ids/templates/cove_oc4ids/explore.html
Fixes: https://github.com/open-contracting/cove-oc4ids/issues/47
=> templates: explore: Add codelist support

cove_oc4ids/templates/cove_oc4ids/additional_checks_table.html, cove_oc4ids/templates/cove_oc4ids/explore.html, requirements.in, requirements.txt
Add three new additional checks to template. This depends on
lib-cove-oc4ids 0.3.0
=> templates: additional_checks_table: Add new additional checks

cove_oc4ids/locale/en/LC_MESSAGES/django.po, cove_oc4ids/locale/es/LC_MESSAGES/django.po, cove_oc4ids/templates/cove_oc4ids/base.html, cove_oc4ids/views.py, cove_project/settings.py, requirements.in, requirements.txt, requirements_dev.txt
https://github.com/open-contracting/cove-oc4ids/issues/59
=> Translate into Spanish

cove_oc4ids/locale/en/LC_MESSAGES/django.po, cove_oc4ids/templates/cove_oc4ids/explore.html, requirements.in, requirements.txt, requirements_dev.txt
Adds new class of checks "conformance checks" . Requires libcoveoc4ids >= 0.3.1.
=> explore: Add conformance_checks

cove_oc4ids/locale/es/LC_MESSAGES/django.po
https://github.com/open-contracting/cove-oc4ids/issues/59
=> locale: Pull latest Spanish translations from transifex

requirements.txt, requirements_dev.txt
https://github.com/open-contracting/cove-oc4ids/issues/80
=> Fix pip-compile again

requirements.in, requirements.txt, requirements_dev.txt
https://github.com/OpenDataServices/lib-cove-web/pull/60
=> requirements: Install latest libcoveweb to pull in missing translation

.github/workflows/ci.yml, README.md, cove_oc4ids/templates/cove_oc4ids/base.html, cove_oc4ids/test_functional.py, cove_oc4ids/views.py, cove_project/settings.py, requirements.in, requirements.txt, requirements_dev.in, requirements_dev.txt
=> Upgrade to Django 3.2

requirements.txt, requirements_dev.txt
Potential directory-traversal via uploaded files:
https://docs.djangoproject.com/en/2.2/releases/2.2.21/
=> requirements: Update Django for security update

cove_oc4ids/views.py, requirements.txt, requirements_dev.txt, tests/fixtures/codelists.json, tests/test_basic.py
https://github.com/OpenDataServices/lib-cove-web/issues/74
=> Links to codelists - rewrite to OCDS Standard
